version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./models/my_model.h5:/app/models/my_model.h5
      - sqlite_data:/app/data
    environment:
      - FLASK_ENV=development  
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  sqlite_data:
